-- 补齐 question_items VIEW(题库统一读入口, UNION practice+exam 两张实体表)。
-- 该 VIEW 此前仅存在于线上库, 未纳入迁移, 新环境从零建库会缺此对象导致题库查询 500。
CREATE OR REPLACE VIEW "question_items" AS
 SELECT practice_question_items.id,
    'practice'::text AS bank_type,
    practice_question_items.organization_id,
    practice_question_items.question_type,
    practice_question_items.stem,
    practice_question_items.options,
    practice_question_items.answer_key,
    practice_question_items.explanation,
    practice_question_items.knowledge_point,
    practice_question_items.difficulty,
    practice_question_items.source,
    practice_question_items.source_version,
    practice_question_items.review_status,
    practice_question_items.reviewer_id,
    practice_question_items.published_version,
    practice_question_items.practice_only,
    practice_question_items.legal_review_required,
    false AS eligible_for_formal_exam,
    NULL::character varying AS created_by,
    practice_question_items.import_job_id,
    practice_question_items.content_hash,
    practice_question_items.created_at,
    practice_question_items.updated_at,
    practice_question_items.deleted_at
   FROM practice_question_items
UNION ALL
 SELECT exam_question_items.id,
    'exam'::text AS bank_type,
    exam_question_items.organization_id,
    exam_question_items.question_type,
    exam_question_items.stem,
    exam_question_items.options,
    exam_question_items.answer_key,
    exam_question_items.explanation,
    exam_question_items.knowledge_point,
    exam_question_items.difficulty,
    exam_question_items.source,
    exam_question_items.source_version,
    exam_question_items.review_status,
    exam_question_items.reviewer_id,
    exam_question_items.published_version,
    exam_question_items.practice_only,
    exam_question_items.legal_review_required,
    exam_question_items.eligible_for_formal_exam,
    NULL::character varying AS created_by,
    exam_question_items.import_job_id,
    exam_question_items.content_hash,
    exam_question_items.created_at,
    exam_question_items.updated_at,
    exam_question_items.deleted_at
   FROM exam_question_items;
