'use client';

import { useCallback, useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Image as ImageIcon, AudioLines, Loader2, ShieldCheck, Upload, XCircle } from 'lucide-react';
import { toast } from 'sonner';
import { apiBlob, apiFetch } from '@/lib/session-client';

interface Asset { id:string; media_kind:'image'|'audio'; checksum:string; version:number; status:string; review_notes?:string|null; transcript?:string|null; category?:string|null; meta?:Record<string,unknown>; created_at:string }
interface GenerationResult { assetId:string; previewUrl:string; checksum:string; status:string; provider:string }

export default function MediaStudioPage(){
  const [kind,setKind]=useState<'image'|'audio'>('image'); const [prompt,setPrompt]=useState(''); const [speaker,setSpeaker]=useState('zh_female_xiaohe_uranus_bigtts'); const [size,setSize]=useState('2K'); const [category,setCategory]=useState('exam-training'); const [targetBank,setTargetBank]=useState<'practice'|'exam'>('practice');
  const [assets,setAssets]=useState<Asset[]>([]); const [loading,setLoading]=useState(false); const [preview,setPreview]=useState<{id:string;url:string;kind:'image'|'audio'}|null>(null); const [notes,setNotes]=useState('已核对主体、类别与清晰度'); const [transcript,setTranscript]=useState('');
  const load=useCallback(async()=>{const r=await apiFetch<Asset[]>('/api/admin/media/assets');if(r.ok&&r.data)setAssets(r.data);},[]); useEffect(()=>{void load()},[load]);
  useEffect(()=>()=>{if(preview?.url)URL.revokeObjectURL(preview.url)},[preview]);
  const open=async(asset:Asset)=>{const r=await apiBlob(`/api/admin/media/assets?id=${asset.id}`);if(!r.ok||!r.blob)return toast.error(r.error??'预览失败');if(preview?.url)URL.revokeObjectURL(preview.url);setPreview({id:asset.id,url:URL.createObjectURL(r.blob),kind:asset.media_kind});setTranscript(asset.transcript??'');};
  const generate=async()=>{if(prompt.trim().length<2)return toast.error(kind==='image'?'请输入图片描述':'请输入旁白或转写文本');setLoading(true);const path=kind==='image'?'/api/admin/media/generate-image':'/api/admin/media/generate-audio';const body=kind==='image'?{prompt,size,category,targetBank}:{text:prompt,speaker,category,targetBank};const r=await apiFetch<GenerationResult>(path,{method:'POST',body});setLoading(false);if(!r.ok||!r.data)return toast.error('生成失败',{description:r.error});toast.success(`素材已生成，Provider：${r.data.provider}。发布前必须人工审核。`);setPrompt('');await load();const asset=(await apiFetch<Asset[]>('/api/admin/media/assets')).data?.find(a=>a.id===r.data!.assetId);if(asset)void open(asset);};
  const review=async(assetId:string,action:'approve'|'reject'|'publish')=>{if(notes.trim().length<2)return toast.error('请填写审核意见');const r=await apiFetch('/api/admin/media/assets',{method:'PATCH',body:{assetId,action,reviewNotes:notes,transcript:transcript||undefined}});if(!r.ok)return toast.error('操作失败',{description:r.error});toast.success(action==='approve'?'审核通过':action==='publish'?'素材已冻结发布':'素材已退回');void load();};
  const current=assets.find(a=>a.id===preview?.id);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">素材工坊</h1><p className="text-muted-foreground mt-1">优先调用 image2-api 与 mimo-lecture-audio-skill；考试素材需经过审核、版本冻结与 checksum 固化。</p></div>
    <div className="flex gap-2"><Button variant={kind==='image'?'default':'outline'} onClick={()=>setKind('image')}><ImageIcon className="w-4 h-4 mr-2"/>图片</Button><Button variant={kind==='audio'?'default':'outline'} onClick={()=>setKind('audio')}><AudioLines className="w-4 h-4 mr-2"/>音频</Button></div>
    <div className="grid lg:grid-cols-[1fr_1.2fr] gap-6"><Card><CardHeader><CardTitle>{kind==='image'?'生成图片素材':'生成讲解/转写音频'}</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>{kind==='image'?'生成描述':'文本（音频标准转写）'}</Label><Textarea rows={6} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={kind==='image'?'主体清晰、背景简洁的篮球/足球、人物、动物或红绿灯图片':'例如：嗯，今天天气很好啊。'}/></div><div className="grid grid-cols-2 gap-3"><div><Label>素材分类</Label><Input value={category} onChange={e=>setCategory(e.target.value)}/></div><div><Label>目标题库</Label><Select value={targetBank} onValueChange={v=>setTargetBank(v as 'practice'|'exam')}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="practice">练习库</SelectItem><SelectItem value="exam">考试库</SelectItem></SelectContent></Select></div>{kind==='image'?<div className="col-span-2"><Label>分辨率</Label><Select value={size} onValueChange={setSize}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="2K">2K</SelectItem><SelectItem value="4K">4K</SelectItem></SelectContent></Select></div>:<div className="col-span-2"><Label>音色</Label><Select value={speaker} onValueChange={setSpeaker}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="zh_female_xiaohe_uranus_bigtts">小何</SelectItem><SelectItem value="zh_female_vv_uranus_bigtts">Vivi</SelectItem><SelectItem value="zh_male_m191_uranus_bigtts">云舟</SelectItem></SelectContent></Select></div>}</div><Button className="w-full" disabled={loading} onClick={generate}>{loading?<><Loader2 className="w-4 h-4 mr-2 animate-spin"/>生成并存档</>:<><Upload className="w-4 h-4 mr-2"/>生成素材</>}</Button></CardContent></Card>
      <Card><CardHeader><CardTitle>预览与审核</CardTitle></CardHeader><CardContent className="space-y-4">{!preview?<div className="py-20 text-center text-muted-foreground">从下方素材列表选择一项预览</div>:<>{preview.kind==='image'?<img src={preview.url} alt="待审核素材" className="max-h-[360px] w-full object-contain rounded border"/>:<audio controls src={preview.url} className="w-full"/>}{current?.media_kind==='audio'&&<div><Label>标准转写（发布音频必填）</Label><Textarea value={transcript} onChange={e=>setTranscript(e.target.value)}/></div>}<div><Label>审核意见</Label><Input value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>review(preview.id,'approve')}><ShieldCheck className="w-4 h-4 mr-1"/>审核通过</Button><Button variant="destructive" onClick={()=>review(preview.id,'reject')}><XCircle className="w-4 h-4 mr-1"/>退回</Button><Button disabled={current?.status!=='reviewed'} onClick={()=>review(preview.id,'publish')}>冻结并发布</Button></div></>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>素材清单</CardTitle></CardHeader><CardContent><div className="divide-y">{assets.length===0?<div className="py-10 text-center text-muted-foreground">暂无素材</div>:assets.map(a=><button key={a.id} onClick={()=>void open(a)} className="w-full py-3 flex items-center justify-between text-left hover:bg-muted/40 px-2 rounded"><div><div className="font-medium">{a.media_kind==='image'?'图片':'音频'} · {a.category||'未分类'} · v{a.version}</div><div className="text-xs text-muted-foreground font-mono">SHA-256 {a.checksum.slice(0,24)}…</div></div><Badge variant={a.status==='published'?'default':'secondary'}>{a.status}</Badge></button>)}</div></CardContent></Card>
  </div>;
}
